# Generated by Django 2.2.24 on 2021-09-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.CharField(default='https://cdn4.iconfinder.com/data/icons/professions-1-2/151/8-512.png', max_length=256, null=True),
        ),
    ]
